### ISSUE TITLE
关于深度操作系统镜像站同步方式

### ISSUE THREAD

**Issue by 21wmd** [AlynxZhou/bjtu-mirror-issues#2]
您好，我是深度社区的管理员Azlar，同时也负责软件仓库的管理和对外联系，打扰您主要是关于深度操作系统镜像站同步方式的问题。我们发现很多镜像站会通过 packages.deepin.com 来进行同步，而不是通过 rsync.deepin.com。rsync.deepin.con 的作用主要就是向镜像站点提供同步的服务，而 packages.deepin.com 的主要作用则是向操作系统提供软件源的服务。如果镜像站通过 packages.deepin.com 来进行同步，可能会影响操作系统软件源的正常使用。我们也正是为保障软件源的问题，才单独提供了 rsync.deepin.com 的服务器。目前，通过 packages.deepin.com 进行镜像站点的同步，已经影响到软件源的正常使用了。所以，我们将在2018年10月31日后，关闭 packages.deepin.com 的rsync同步功能。
所以得麻烦您检查一下您的同步方式，如果是从 rsync.deepin.com 中同步，您可以忽略这封邮件。如果是从 packages.deepin.com 中同步，那就需要您修改一下同步的方式，我们会在2018年10月31日后，关闭 packages.deepin.com 的rsync同步功能，同步命令如下：
rsync -av --delete-after rsync.deepin.com::deepin/ /var/www/deepin/
rsync -av --delete-after rsync.deepin.com::releases/ /var/www/deepin-cd/

**Comment by ideal** [comment]
@AlynxZhou 改下配置里的upstream？

**Comment by AlynxZhou** [comment]
我记得我看过是没问题的，然后就真的 **忽略** 这个邮件了…

**Comment by chestnutprog** [comment]
已修复……
